unused_cols = [
    'UF_ZI',
    'ANO_CMPT',
    'MES_CMPT',
    'ESPEC',
    'N_AIH',
    'IDENT',
    'UTI_MES_IN',
    'UTI_MES_AN',
    'UTI_MES_AL',
    'MARCA_UTI',
    'UTI_INT_IN',
    'UTI_INT_AN',
    'UTI_INT_AL',
    'DIAR_ACOM',
    'QT_DIARIAS',
    'PROC_SOLIC',
    'PROC_REA',
    'VAL_SADT',
    'VAL_RN',
    'VAL_ACOMP',
    'VAL_ORTP',
    'VAL_SANGUE',
    'VAL_SADTSR',
    'VAL_TRANSP',
    'VAL_OBSANG',
    'VAL_PED1AC',
    'VAL_TOT',
    'VAL_UTI',
    'US_TOT',
    'DT_SAIDA',
    'COBRANCA',
    'NATUREZA',
    'NAT_JUR',
    'GESTAO',
    'RUBRICA',
    'IND_VDRL',
    'COD_IDADE',
    'IDADE',
    'NUM_PROC',
    'CAR_INT',
    'TOT_PT_SP',
    'CPF_AUT',
    'HOMONIMO',
    'NUM_FILHOS',
    'CID_NOTIF',
    'CONTRACEP1',
    'CONTRACEP2',
    'GESTRISCO',
    'SEQ_AIH5',
    'CBOR',
    'CNAER',
    'VINCPREV',
    'GESTOR_COD',
    'GESTOR_TP',
    'GESTOR_CPF',
    'GESTOR_DT',
    'CNPJ_MANT',
    'INFEHOSP',
    'CID_ASSO',
    'CID_MORTE',
    'COMPLEX',
    'FINANC',
    'FAEC_TP',
    'REGCT',
    'SEQUENCIA',
    'REMESSA',
    'AUD_JUST',
    'SIS_JUST',
    'VAL_SH_FED',
    'VAL_SP_FED',
    'VAL_SH_GES',
    'VAL_SP_GES',
    'VAL_UCI',
    'MARCA_UCI',
    'TPDISEC1',
    'TPDISEC2',
    'TPDISEC3',
    'TPDISEC4',
    'TPDISEC5',
    'TPDISEC6',
    'TPDISEC7',
    'TPDISEC8',
    'TPDISEC9',
]

resp_diseases = {
    'J00': 'Nasofaringite aguda                          J00 -J009',
    'J01': 'Sinusite aguda                               J01 -J019',
    'J010': 'Sinusite maxilar aguda                       J010',
    'J011': 'Sinusite frontal aguda                       J011',
    'J012': 'Sinusite etmoidal aguda                      J012',
    'J013': 'Sinusite esfenoidal aguda                    J013',
    'J014': 'Pansinusite aguda                            J014',
    'J018': 'Outr sinusites agudas                        J018',
    'J019': 'Sinusite aguda NE                            J019',
    'J02': 'Faringite aguda                              J02 -J029',
    'J020': 'Faringite estreptococica                     J020',
    'J028': 'Faringite aguda dev outr microorg espec      J028',
    'J029': 'Faringite aguda NE                           J029',
    'J03': 'Amigdalite aguda                             J03 -J039',
    'J030': 'Amigdalite estreptococica                    J030',
    'J038': 'Amigdalite aguda dev outr microorg espec     J038',
    'J039': 'Amigdalite aguda NE                          J039',
    'J04': 'Laringite e traqueite agudas                 J04 -J049',
    'J040': 'Laringite aguda                              J040',
    'J041': 'Traqueite aguda                              J041',
    'J042': 'Laringotraqueite aguda                       J042',
    'J05': 'Laringite obstrutiva aguda e epiglotite      J05 -J059',
    'J050': 'Laringite obstrutiva aguda                   J050',
    'J051': 'Epiglotite aguda                             J051',
    'J06': 'Infecc agudas vias aereas super loc mult NE  J06 -J069',
    'J060': 'Laringofaringite aguda                       J060',
    'J068': 'Outr infecc agudas vias aereas sup loc mult  J068',
    'J069': 'Infecc aguda das vias aereas super NE        J069',
    'J09': 'Influenza dev virus gripe aviária            J09 -J099',
    'J10': 'Influenza dev outro virus influenza ident    J10 -J109',
    'J100': 'Influenza c/pneum dev outr virus influ ident J100',
    'J101': 'Influenz c/out manif resp out vir infl ident J101',
    'J108': 'Influenza c/out manif dev out vir infl ident J108',
    'J11': 'Influenza dev virus nao identificado         J11 -J119',
    'J110': 'Influenza c/pneumonia dev virus nao ident    J110',
    'J111': 'Influenza c/out manif resp dev virus n ident J111',
    'J118': 'Influenza c/outr manif dev virus nao ident   J118',
    'J12': 'Pneumonia viral NCOP                         J12 -J129',
    'J120': 'Pneumonia dev adenovirus                     J120',
    'J121': 'Pneumonia dev virus respirat sincicial       J121',
    'J122': 'Pneumonia dev parainfluenza                  J122',
    'J128': 'Outr pneumonias virais                       J128',
    'J129': 'Pneumonia viral NE                           J129',
    'J13': 'Pneumonia dev Streptococcus pneumoniae       J13 -J139',
    'J14': 'Pneumonia dev Haemophilus infuenzae          J14 -J149',
    'J15': 'Pneumonia bacter NCOP                        J15 -J159',
    'J150': 'Pneumonia dev Klebsiella pneumoniae          J150',
    'J151': 'Pneumonia dev Pseudomonas                    J151',
    'J152': 'Pneumonia dev Staphylococcus                 J152',
    'J153': 'Pneumonia dev Streptococcus do grupo B       J153',
    'J154': 'Pneumonia dev outr estreptococos             J154',
    'J155': 'Pneumonia dev Escherichia coli               J155',
    'J156': 'Pneumonia dev outr bact aerobicas gram-neg   J156',
    'J157': 'Pneumonia dev Mycoplasma pneumoniae          J157',
    'J158': 'Outr pneumonias bacter                       J158',
    'J159': 'Pneumonia bacter NE                          J159',
    'J16': 'Pneumonia dev out microorg infecc espec NCOP J16 -J169',
    'J160': 'Pneumonia dev clamidias                      J160',
    'J168': 'Pneumonia dev outr microorg infecc espec     J168',
    'J17': 'Pneumonia em doenc COP                       J17 -J179',
    'J170': 'Pneumonia em doenc bacter COP                J170',
    'J171': 'Pneumonia em doenc virais COP                J171',
    'J172': 'Pneumonia em micoses COP                     J172',
    'J173': 'Pneumonia em doenc parasit COP               J173',
    'J178': 'Pneumonia em outr doenc COP                  J178',
    'J18': 'Pneumonia p/microorg NE                      J18 -J189',
    'J180': 'Broncopneumonia NE                           J180',
    'J181': 'Pneumonia lobar NE                           J181',
    'J182': 'Pneumonia hipostatica NE                     J182',
    'J188': 'Outr pneumonias dev microorg NE              J188',
    'J189': 'Pneumonia NE                                 J189',
    'J20': 'Bronquite aguda                              J20 -J209',
    'J200': 'Bronquite aguda dev Mycoplasma pneumoniae    J200',
    'J201': 'Bronquite aguda dev Haemophilus influenzae   J201',
    'J202': 'Bronquite aguda dev estreptococos            J202',
    'J203': 'Bronquite aguda dev virus Coxsackie          J203',
    'J204': 'Bronquite aguda dev virus parainfluenza      J204',
    'J205': 'Bronquite aguda dev virus sincicial respirat J205',
    'J206': 'Bronquite aguda dev rinovirus                J206',
    'J207': 'Bronquite aguda dev echovirus                J207',
    'J208': 'Bronquite aguda dev outr microorg espec      J208',
    'J209': 'Bronquite aguda NE                           J209',
    'J21': 'Bronquiolite aguda                           J21 -J219',
    'J210': 'Bronquiolite aguda dev virus sincicial resp  J210',
    'J218': 'Bronquiolite aguda dev outr microorg espec   J218',
    'J219': 'Bronquite aguda NE                           J219',
    'J22': 'Infecc agudas NE das vias aereas infer       J22 -J229',
    'J30': 'Rinite alergica e vasomotora                 J30 -J309',
    'J300': 'Rinite vasomotora                            J300',
    'J301': 'Rinite alergica dev polen                    J301',
    'J302': 'Outr rinites alergicas sazonais              J302',
    'J303': 'Outr rinites alergicas                       J303',
    'J304': 'Rinite alergica NE                           J304',
    'J31': 'Rinite nasofaringite e faringite cronicas    J31 -J319',
    'J310': 'Rinite cronica                               J310',
    'J311': 'Nasofaringite cronica                        J311',
    'J312': 'Faringite cronica                            J312',
    'J32': 'Sinusite cronica                             J32 -J329',
    'J320': 'Sinusite maxilar cronica                     J320',
    'J321': 'Sinusite frontal cronica                     J321',
    'J322': 'Sinusite etmoidal cronica                    J322',
    'J323': 'Sinusite esfenoidal cronica                  J323',
    'J324': 'Pansinusite cronica                          J324',
    'J328': 'Outr sinusites cronicas                      J328',
    'J329': 'Sinusite cronica NE                          J329',
    'J33': 'Polipo nasal                                 J33 -J339',
    'J330': 'Polipo da cavidade nasal                     J330',
    'J331': 'Degeneracao polipoide do seio paranasal      J331',
    'J338': 'Outr polipos do seio paranasal               J338',
    'J339': 'Polipo nasal NE                              J339',
    'J34': 'Outr transt do nariz e dos seios paranasais  J34 -J349',
    'J340': 'Abscesso furunculo e antraz do nariz         J340',
    'J341': 'Cisto e mucocele do nariz e seio paranasal   J341',
    'J342': 'Desvio do septo nasal                        J342',
    'J343': 'Hipertrofia dos cornetos nasais              J343',
    'J348': 'Outr transt espec nariz e seios paranasais   J348',
    'J35': 'Doenc cronicas das amigdalas e das adenoides J35 -J359',
    'J350': 'Amigdalite cronica                           J350',
    'J351': 'Hipertrofia das amigdalas                    J351',
    'J352': 'Hipertrofia das adenoides                    J352',
    'J353': 'Hipertrofia amigdalas c/hipertrof adenoides  J353',
    'J358': 'Outr doenc cronicas amigdalas e adenoides    J358',
    'J359': 'Doenc das amigdalas e das adenoides NE       J359',
    'J36': 'Abscesso periamigdaliano                     J36 -J369',
    'J37': 'Laringite e laringotraqueite cronicas        J37 -J379',
    'J370': 'Laringite cronica                            J370',
    'J371': 'Laringotraqueite cronica                     J371',
    'J38': 'Doenc das cordas vocais e da laringe NCOP    J38 -J389',
    'J380': 'Paralisia das cordas vocais e da laringe     J380',
    'J381': 'Polipo das cordas vocais e da laringe        J381',
    'J382': 'Nodulos das cordas vocais                    J382',
    'J383': 'Outr doenc das cordas vocais                 J383',
    'J384': 'Edema da laringe                             J384',
    'J385': 'Espasmo da laringe                           J385',
    'J386': 'Estenose da laringe                          J386',
    'J387': 'Outr doenc da laringe                        J387',
    'J39': 'Outr doenc das vias aereas super             J39 -J399',
    'J390': 'Abscesso retrofaringeo e parafaringeo        J390',
    'J391': 'Outr abscessos da faringe                    J391',
    'J392': 'Outr doenc da faringe                        J392',
    'J393': 'Reacao hipersensib vias aereas super loc NE  J393',
    'J398': 'Outr doenc espec das vias aereas super       J398',
    'J399': 'Doenc NE das vias aereas super               J399',
    'J40': 'Bronquite NE como aguda ou cronica           J40 -J409',
    'J41': 'Bronquite cronica simples e a mucopurulenta  J41 -J419',
    'J410': 'Bronquite cronica simples                    J410',
    'J411': 'Bronquite cronica mucopurulenta              J411',
    'J418': 'Bronquite cron mista simples e mucopurulenta J418',
    'J42': 'Bronquite cronica NE                         J42 -J429',
    'J43': 'Enfisema                                     J43 -J439',
    'J430': 'Sindr de MacLeod                             J430',
    'J431': 'Enfisema panlobular                          J431',
    'J432': 'Enfisema centrolobular                       J432',
    'J438': 'Outr form de enfisema                        J438',
    'J439': 'Enfisema NE                                  J439',
    'J44': 'Outr doenc pulmonares obstrutivas cronicas   J44 -J449',
    'J440': 'Doen pulm obs cron c/inf resp ag tr resp inf J440',
    'J441': 'Doenc pulmonar obstr cron c/exacerb aguda NE J441',
    'J448': 'Outr form espec doenc pulmonar obstrut cron  J448',
    'J449': 'Doenc pulmonar obstrutiva cronica NE         J449',
    'J45': 'Asma                                         J45 -J459',
    'J450': 'Asma predom alergica                         J450',
    'J451': 'Asma nao-alergica                            J451',
    'J458': 'Asma mista                                   J458',
    'J459': 'Asma NE                                      J459',
    'J46': 'Estado de mal asmatico                       J46 -J469',
    'J47': 'Bronquectasia                                J47 -J479',
    'J60': 'Pneumoconiose dos mineiros de carvao         J60 -J609',
    'J61': 'Pneumoconiose dev amianto outr fibr minerais J61 -J619',
    'J62': 'Pneumoconiose dev poeira que cont silica     J62 -J629',
    'J620': 'Pneumoconiose dev po de talco                J620',
    'J628': 'Pneumoconiose dev outr poeiras q cont silica J628',
    'J63': 'Pneumoconiose dev outr poeiras inorganicas   J63 -J639',
    'J630': 'Aluminose                                    J630',
    'J631': 'Fibrose causada p/bauxita                    J631',
    'J632': 'Beriliose                                    J632',
    'J633': 'Fibrose causada p/grafite                    J633',
    'J634': 'Siderose                                     J634',
    'J635': 'Estanose                                     J635',
    'J638': 'Pneumoconiose dev outr poeira inorg espec    J638',
    'J64': 'Pneumoconiose NE                             J64 -J649',
    'J65': 'Pneumoconiose assoc c/tuberc                 J65 -J659',
    'J66': 'Doenc das vias aereas dev poeiras org espec  J66 -J669',
    'J660': 'Bissinose                                    J660',
    'J661': 'Doenc dos cardadores de linho                J661',
    'J662': 'Canabinose                                   J662',
    'J668': 'Doenc vias aereas dev outr poeiras org espec J668',
    'J67': 'Pneumonite hipersensibilid dev poeiras org   J67 -J679',
    'J670': 'Pulmao de fazendeiro                         J670',
    'J671': 'Bagacose                                     J671',
    'J672': 'Pulmao dos criadores de passaros             J672',
    'J673': 'Suberose                                     J673',
    'J674': 'Pulmao dos trabalhadores do malte            J674',
    'J675': 'Pulmao dos que trabalham c/cogumelos         J675',
    'J676': 'Pulmao dos cortadores de casca do bordo      J676',
    'J677': 'Doenc pulmonar dev sist ar cond umidif ar    J677',
    'J678': 'Pneumonites hipersens dev outr poeiras org   J678',
    'J679': 'Pneumonite hipersensibilid dev poeira org NE J679',
    'J68': 'Afecc resp dev inal prod quim gas fumac vap  J68 -J689',
    'J680': 'Bronquit pneumon dev prod quim gas fumac vap J680',
    'J681': 'Edema pulm dev prod quim gas fumac vap       J681',
    'J682': 'Infl via aer sup dev pr qui gas fum vap NCOP J682',
    'J683': 'Out af resp ag subag dev pro qui gas fum vap J683',
    'J684': 'Afecc resp cron dev prod quim gas fum vap    J684',
    'J688': 'Outr afecc resp dev prod quim gas fum vap    J688',
    'J689': 'Afecc resp NE dev prod quim gases fumac vap  J689',
    'J69': 'Pneumonite dev solidos e liquidos            J69 -J699',
    'J690': 'Pneumonite dev alimento ou vomito            J690',
    'J691': 'Pneumonite dev oleos e essencias             J691',
    'J698': 'Pneumonite dev outr solidos e liquidos       J698',
    'J70': 'Afeccoes respirat dev outr agentes externos  J70 -J709',
    'J700': 'Manifestacoes pulmonares agudas dev radiacao J700',
    'J701': 'Manif pulmonares cron e outr dev radiacao    J701',
    'J702': 'Transt pulm interstic agudos induz p/droga   J702',
    'J703': 'Transt pulm interstic cronicos induz p/droga J703',
    'J704': 'Transt pulm intersticial NE induz p/droga    J704',
    'J708': 'Afecc respirat dev outr agent externos espec J708',
    'J709': 'Afeccoes respirat dev agentes externos NE    J709',
    'J80': 'Sindr do desconforto respirat do adulto      J80 -J809',
    'J81': 'Edema pulmonar NE de outr form               J81 -J819',
    'J82': 'Eosinofilia pulmonar NCOP                    J82 -J829',
    'J84': 'Outr doenc pulmonares intersticiais          J84 -J849',
    'J840': 'Afeccoes alveolares e parieto-alveolares     J840',
    'J841': 'Outr doenc pulm intersticiais c/fibrose      J841',
    'J848': 'Outr doenc pulmonares intersticiais espec    J848',
    'J849': 'Doenc pulmonar intersticial NE               J849',
    'J85': 'Abscesso do pulmao e do mediastino           J85 -J859',
    'J850': 'Gangrena e necrose do pulmao                 J850',
    'J851': 'Abscesso do pulmao c/pneumonia               J851',
    'J852': 'Abscesso do pulmao s/pneumonia               J852',
    'J853': 'Abscesso do mediastino                       J853',
    'J86': 'Piotorax                                     J86 -J869',
    'J860': 'Piotorax c/fistula                           J860',
    'J869': 'Piotorax s/fistula                           J869',
    'J90': 'Derrame pleural NCOP                         J90 -J909',
    'J91': 'Derrame pleural em afeccoes COP              J91 -J919',
    'J92': 'Placas pleurais                              J92 -J929',
    'J920': 'Placas pleurais c/presenca de amianto        J920',
    'J929': 'Placas pleurais cem presenca de amianto      J929',
    'J93': 'Pneumotorax                                  J93 -J939',
    'J930': 'Pneumotorax de tensao espontaneo             J930',
    'J931': 'Outr form de pneumotorax espontaneo          J931',
    'J938': 'Outr tipos de pneumotorax espec              J938',
    'J939': 'Pneumotorax NE                               J939',
    'J94': 'Outr afeccoes pleurais                       J94 -J949',
    'J940': 'Derrame quiloso ou quiliforme                J940',
    'J941': 'Fibrotorax                                   J941',
    'J942': 'Hemotorax                                    J942',
    'J948': 'Outr afeccoes pleurais espec                 J948',
    'J949': 'Afeccao pleural NE                           J949',
    'J95': 'Afeccoes respirat pos-proced NCOP            J95 -J959',
    'J950': 'Mau funcionamento de traqueostomia           J950',
    'J951': 'Insuf pulmonar aguda subseq cirurg toracica  J951',
    'J952': 'Insuf pulm aguda subseq cirurg nao toracica  J952',
    'J953': 'Insuf pulmonar cronica pos-cirurgica         J953',
    'J954': 'Sindr de Mendelson                           J954',
    'J955': 'Estenose subglotica pos-proced               J955',
    'J958': 'Outr transt respirat pos-proced              J958',
    'J959': 'Transt respirat pos-proced NE                J959',
    'J96': 'Insuf respirat NCOP                          J96 -J969',
    'J960': 'Insuf respirat aguda                         J960',
    'J961': 'Insuf respirat cronica                       J961',
    'J969': 'Insuf respirat NE                            J969',
    'J98': 'Outr transt respirat                         J98 -J989',
    'J980': 'Outr doenc dos bronquios NCOP                J980',
    'J981': 'Colapso pulmonar                             J981',
    'J982': 'Enfisema intersticial                        J982',
    'J983': 'Enfisema compensatorio                       J983',
    'J984': 'Outr transt pulmonares                       J984',
    'J985': 'Doenc do mediastino NCOP                     J985',
    'J986': 'Transt do diafragma                          J986',
    'J988': 'Outr transt respirat espec                   J988',
    'J989': 'Transt respirat NE                           J989',
    'J99': 'Transt respirat em doenc COP                 J99 -J999',
    'J990': 'Doenc pulmonar reumatoide                    J990',
    'J991': 'Transt respirat outr doenc sist tec conj COP J991',
    'J998': 'Transt respirat em outr doenc COP            J998',
}

diseases_cols = [
    'DIAG_PRINC',
    'DIAG_SECUN',
    'DIAGSEC1',
    'DIAGSEC2',
    'DIAGSEC3',
    'DIAGSEC4',
    'DIAGSEC5',
    'DIAGSEC6',
    'DIAGSEC7',
    'DIAGSEC8',
    'DIAGSEC9'
]

cities_mrs = {
    '292740': 'Salvador',
    '290570': 'Camaçari',
    '292920': 'São Francisco do Conde',
    '291920': 'Lauro de Freitas',
    '293070': 'Simões Filho',
    '290650': 'Candeias',
    '291005': "Dias d'Ávila",
    '292100': 'Mata de São João',
    '292520': 'Pojuca',
    '292950': 'São Sebastião do Passé',
    '293320': 'Vera Cruz',
    '291992': 'Madre de Deus',
    '291610': 'Itaparica'
}
cities_cols = ['MUNIC_RES', 'MUNIC_MOV']